markdown: GFM
remote_theme: just-the-docs/just-the-docs
aux_links:
  "Contribute":
    - "https://github.com/PrashantMohta/ModdingDocs"
  "Join Modding Discord":
    - "https://discord.gg/RppAb2vNqz"
